"""add salon approval and owner fields

Revision ID: 330574bf2d44
Revises: 2cc26bcda3fd
Create Date: 2026-09-01 11:43:38.202719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '330574bf2d44'
down_revision: Union[str, Sequence[str], None] = '2cc26bcda3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salons', sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('salons', sa.Column('owner_telegram_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salons', 'owner_telegram_id')
    op.drop_column('salons', 'is_approved')
    # ### end Alembic commands ###
