"""add languagae to masters

Revision ID: 4ce6e0ee15bb
Revises: e8ccb7da4191
Create Date: 2026-08-06 20:59:39.762741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce6e0ee15bb'
down_revision: Union[str, Sequence[str], None] = 'e8ccb7da4191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "masters",
    sa.Column(
        "language",
        sa.String(length=5),
        nullable=False,
        server_default="uz",
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masters', 'language')
    # ### end Alembic commands ###
