"""add blocked status and nullable fields for time blocking

Revision ID: 51cdf139c9b1
Revises: 4ce6e0ee15bb
Create Date: 2026-08-07 13:35:54.679961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51cdf139c9b1'
down_revision: Union[str, Sequence[str], None] = '4ce6e0ee15bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
