"""make master salon_id nullbale

Revision ID: b3f490565c6c
Revises: 330574bf2d44
Create Date: 2026-09-03 08:39:43.578033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f490565c6c'
down_revision: Union[str, Sequence[str], None] = '330574bf2d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('masters', 'salon_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('masters', 'salon_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
