"""add phone to masters

Revision ID: e8ccb7da4191
Revises: 0d6ae499ce0c
Create Date: 2026-08-06 20:43:36.484124

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8ccb7da4191"
down_revision: Union[str, Sequence[str], None] = "0d6ae499ce0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("masters", sa.Column("phone", sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, "masters", ["phone"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "masters", type_="unique")
    op.drop_column("masters", "phone")
    # ### end Alembic commands ###
